version: '3.8'
services:
  backend:
    build: .
    ports:
    - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017/UserDb
      PORT: 8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - backend-nodejs:/data/db
volumes:
  backend-nodejs:
  